export const dataHeight = {
  datasets: [
    {
      label: "Rất thấp",
      data: [
        { x: 140, y: 1 },
        { x: 150, y: 1 },
        { x: 155, y: 0 },
      ],
      borderColor: "red",
      borderWidth: 2,
      backgroundColor: "red",
      pointBackgroundColor: "red",
      pointBorderColor: "red",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Thấp",
      data: [
        { x: 150, y: 0 },
        { x: 155, y: 1 },
        { x: 160, y: 1 },
        { x: 165, y: 0 },
      ],
      borderColor: "blue",
      borderWidth: 2,
      backgroundColor: "blue",
      pointBackgroundColor: "blue",
      pointBorderColor: "blue",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Trung bình",
      data: [
        { x: 160, y: 0 },
        { x: 165, y: 1 },
        { x: 173, y: 1 },
        { x: 175, y: 0 },
      ],
      borderColor: "green",
      borderWidth: 2,
      backgroundColor: "green",
      pointBackgroundColor: "green",
      pointBorderColor: "green",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Cao",
      data: [
        { x: 173, y: 0 },
        { x: 175, y: 1 },
        { x: 180, y: 1 },
        { x: 185, y: 0 },
      ],
      borderColor: "orange",
      borderWidth: 2,
      backgroundColor: "orange",
      pointBackgroundColor: "orange",
      pointBorderColor: "orange",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Rất cao",
      data: [
        { x: 180, y: 0 },
        { x: 185, y: 1 },
        { x: 190, y: 1 },
      ],
      borderColor: "purple",
      borderWidth: 2,
      backgroundColor: "purple",
      pointBackgroundColor: "purple",
      pointBorderColor: "purple",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
  ],
};
export const dataWeight = {
  datasets: [
    {
      label: "Rất nhẹ",
      data: [
        { x: 40, y: 1 },
        { x: 44, y: 1 },
        { x: 49, y: 0 },
      ],
      borderColor: "red",
      borderWidth: 2,
      backgroundColor: "red",
      pointBackgroundColor: "red",
      pointBorderColor: "red",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Nhẹ",
      data: [
        { x: 44, y: 0 },
        { x: 52, y: 1 },
        { x: 54, y: 1 },
        { x: 59, y: 0 },
      ],
      borderColor: "blue",
      borderWidth: 2,
      backgroundColor: "blue",
      pointBackgroundColor: "blue",
      pointBorderColor: "blue",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },

    {
      label: "Trung bình",
      data: [
        { x: 54, y: 0 },
        { x: 59, y: 1 },
        { x: 66, y: 1 },
        { x: 71, y: 0 },
      ],
      borderColor: "green",
      borderWidth: 2,
      backgroundColor: "green",
      pointBackgroundColor: "green",
      pointBorderColor: "green",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Nặng",
      data: [
        { x: 66, y: 0 },
        { x: 71, y: 1 },
        { x: 74, y: 1 },
        { x: 79, y: 0 },
      ],
      borderColor: "orange",
      borderWidth: 2,
      backgroundColor: "orange",
      pointBackgroundColor: "orange",
      pointBorderColor: "orange",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Rất nặng",
      data: [
        { x: 74, y: 0 },
        { x: 79, y: 1 },
        { x: 90, y: 1 },
      ],
      borderColor: "purple",
      borderWidth: 2,
      backgroundColor: "purple",
      pointBackgroundColor: "purple",
      pointBorderColor: "purple",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
  ],
};
export const dataHeartBeat = {
  datasets: [
    {
      label: "Thấp",
      data: [
        { x: 40, y: 1 },
        { x: 50, y: 1 },
        { x: 55, y: 0 },
      ],
      borderColor: "red",
      borderWidth: 2,
      backgroundColor: "red",
      pointBackgroundColor: "red",
      pointBorderColor: "red",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Bình thường",
      data: [
        { x: 50, y: 0 },
        { x: 60, y: 1 },
        { x: 100, y: 1 },
        { x: 110, y: 0 },
      ],
      borderColor: "blue",
      borderWidth: 2,
      backgroundColor: "blue",
      pointBackgroundColor: "blue",
      pointBorderColor: "blue",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },

    {
      label: "Cao",
      data: [
        { x: 105, y: 0 },
        { x: 110, y: 1 },
        { x: 120, y: 1 },
      ],
      borderColor: "green",
      borderWidth: 2,
      backgroundColor: "green",
      pointBackgroundColor: "green",
      pointBorderColor: "green",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
  ],
};
export const dataBloodPressure = {
  datasets: [
    {
      label: "Thấp",
      data: [
        { x: 60, y: 1 },
        { x: 80, y: 1 },
        { x: 90, y: 0 },
      ],
      borderColor: "red",
      borderWidth: 2,
      backgroundColor: "red",
      pointBackgroundColor: "red",
      pointBorderColor: "red",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Bình thường",
      data: [
        { x: 80, y: 0 },
        { x: 90, y: 1 },
        { x: 120, y: 1 },
        { x: 130, y: 0 },
      ],
      borderColor: "blue",
      borderWidth: 2,
      backgroundColor: "blue",
      pointBackgroundColor: "blue",
      pointBorderColor: "blue",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },

    {
      label: "Cao",
      data: [
        { x: 120, y: 0 },
        { x: 130, y: 1 },
        { x: 140, y: 1 },
      ],
      borderColor: "green",
      borderWidth: 2,
      backgroundColor: "green",
      pointBackgroundColor: "green",
      pointBorderColor: "green",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
  ],
};
export const dataBMI = {
  datasets: [
    {
      label: "Thiếu cân",
      data: [
        {x:1,y:0},
        { x: 12, y: 1 },
        { x: 17, y: 1 },
        { x: 18.5, y: 0 },
      ],
      borderColor: "red",
      borderWidth: 2,
      backgroundColor: "red",
      pointBackgroundColor: "red",
      pointBorderColor: "red",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Cân đối",
      data: [
        { x: 18, y: 0 },
        { x: 19, y: 1 },
        { x: 22, y: 1 },
        { x: 24.9, y: 0 },
      ],
      borderColor: "blue",
      borderWidth: 2,
      backgroundColor: "blue",
      pointBackgroundColor: "blue",
      pointBorderColor: "blue",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Tiền béo phì",
      data: [
        { x: 24, y: 0 },
        { x: 26, y: 1 },
        { x: 28, y: 1 },
        { x: 29.9, y: 0 },
      ],
      borderColor: "green",
      borderWidth: 2,
      backgroundColor: "green",
      pointBackgroundColor: "green",
      pointBorderColor: "green",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Béo phì",
      data: [
        { x: 28, y: 0 },
        { x: 30, y: 1 },
        { x: 32, y: 1 },
        {x:34,y:0},
      ],
      borderColor: "orange",
      borderWidth: 2,
      backgroundColor: "orange",
      pointBackgroundColor: "orange",
      pointBorderColor: "orange",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
  ],
};
export const dataBMI2 = {
  datasets: [
    {
      label: "Thiếu cân",
      data: [
        { x: 1, y: 0 },
        { x: 12, y: 1 },
        { x: 17, y: 1 },
        { x: 18.5, y: 0 },
      ],
      borderColor: "red",
      borderWidth: 2,
      backgroundColor: "red",
      pointBackgroundColor: "red",
      pointBorderColor: "red",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Cân đối",
      data: [
        { x: 18, y: 0 },
        { x: 19, y: 1 },
        { x: 22, y: 1 },
        { x: 24.9, y: 0 },
      ],
      borderColor: "blue",
      borderWidth: 2,
      backgroundColor: "blue",
      pointBackgroundColor: "blue",
      pointBorderColor: "blue",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Tiền béo phì",
      data: [
        { x: 24, y: 0 },
        { x: 26, y: 1 },
        { x: 28, y: 1 },
        { x: 29.9, y: 0 },
      ],
      borderColor: "green",
      borderWidth: 2,
      backgroundColor: "green",
      pointBackgroundColor: "green",
      pointBorderColor: "green",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Béo phì",
      data: [
        { x: 28, y: 0 },
        { x: 30, y: 1 },
        { x: 32, y: 1 },
        { x: 34, y: 0 },
      ],
      borderColor: "orange",
      borderWidth: 2,
      backgroundColor: "orange",
      pointBackgroundColor: "orange",
      pointBorderColor: "orange",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
  ],
};
export const dataHI = {
  datasets: [
    {
      label: "Yếu",
      data: [
        { x: 1, y: 0 },
        { x: 25, y: 1 },
        { x: 45, y: 0 },
      ],
      borderColor: "red",
      borderWidth: 2,
      backgroundColor: "red",
      pointBackgroundColor: "red",
      pointBorderColor: "red",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Không khỏe lắm",
      data: [
        { x: 35, y: 0 },
        { x: 50, y: 1 },
        { x: 70, y: 0 },
      ],
      borderColor: "blue",
      borderWidth: 2,
      backgroundColor: "blue",
      pointBackgroundColor: "blue",
      pointBorderColor: "blue",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Có vẻ khỏe",
      data: [
        { x: 55, y: 0 },
        { x: 75, y: 1 },
        { x: 85, y: 0 },
      ],
      borderColor: "green",
      borderWidth: 2,
      backgroundColor: "green",
      pointBackgroundColor: "green",
      pointBorderColor: "green",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Khỏe",
      data: [
        { x: 80, y: 0 },
        { x: 90, y: 1 },
        { x: 100, y: 0 },
      ],
      borderColor: "orange",
      borderWidth: 2,
      backgroundColor: "orange",
      pointBackgroundColor: "orange",
      pointBorderColor: "orange",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
  ],
};
export const dataHI2 = {
  datasets: [
    {
      label: "Yếu",
      data: [
        { x: 1, y: 0 },
        { x: 25, y: 1 },
        { x: 45, y: 0 },
      ],
      borderColor: "red",
      borderWidth: 2,
      backgroundColor: "red",
      pointBackgroundColor: "red",
      pointBorderColor: "red",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Không khỏe lắm",
      data: [
        { x: 35, y: 0 },
        { x: 50, y: 1 },
        { x: 70, y: 0 },
      ],
      borderColor: "blue",
      borderWidth: 2,
      backgroundColor: "blue",
      pointBackgroundColor: "blue",
      pointBorderColor: "blue",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Có vẻ khỏe",
      data: [
        { x: 55, y: 0 },
        { x: 75, y: 1 },
        { x: 85, y: 0 },
      ],
      borderColor: "green",
      borderWidth: 2,
      backgroundColor: "green",
      pointBackgroundColor: "green",
      pointBorderColor: "green",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
    {
      label: "Khỏe",
      data: [
        { x: 80, y: 0 },
        { x: 90, y: 1 },
        { x: 100, y: 0 },
      ],
      borderColor: "orange",
      borderWidth: 2,
      backgroundColor: "orange",
      pointBackgroundColor: "orange",
      pointBorderColor: "orange",
      pointRadius: 3,
      pointHoverRadius: 5,
      fill: false,
      tension: 0,
      showLine: true,
    },
  ],
};